### ISSUE TITLE
How to receive big and full pack in client?

### ISSUE THREAD

**Issue by leaf918** [fpagliughi/sockpp#101]
when the server send and big image ,size is 112962 bytes, the cleint canoot get it all,
how to solve it ? 
thanks.
 
![image](https://github.com/user-attachments/assets/7c8387fa-c45c-4530-8e29-b00b25f4bd72)

**Comment by fpagliughi** [comment]
I'm not sure what this is...

**Comment by leaf918** [comment]
sorry for my confused question,
this is my client function:
when the server send big pack(more than 100KB),the client will cannot receive it all.
`void handler_client(sockpp::tcp_socket rdSock) {
    char buf[200000];
    std::vector<char> buffer;
    sockpp::result<size_t> res;

    while (true) {
        if (res = rdSock.read(buf, sizeof(buf)); !res || res.value() == 0) {
            cerr << "Read error: " << res.error_message() << endl;
            break;
        } else {
            JV_LOGD("handler_client...%d", res.value());
            buffer.resize(res.value());
            memcpy(buffer.data(), buf, res.value());
            auto msg_in = struct_pack::deserialize<MsgCell>(buffer).value();
            JV_LOGI("Client COPY:: size== %d target== %s", res.value(), msg_in.target.c_str());
            handle_msg_client_side(msg_in, rdSock);

        }
    }
    rdSock.shutdown();
}`

**Comment by fpagliughi** [comment]
Ok. That is a partial (short) read. When you call `read()` the OS will typically block until it has _some_ data give you, up to the amount you requested (i.e. the size of your buffer), but it can always give you less. So you need to repeatedly call `read()`, appending any new data into your buffer, until you have the full packet that you're expecting or you get an error.

If you know size of your packet in advance, you can call `read_n()` which will repeatedly call read until the requested number of bytes are received or an error occurs. It's also a good example of how to do it yourself:
https://github.com/fpagliughi/sockpp/blob/04002daccc8f66a77edf019124089a3ce966b2e3/src/stream_socket.cpp#L72-L89

I should note that this _sockpp_ library is just a thin wrapper around the C Berkeley socket API. What I mentioned here is fairly standard socket programming limitations. Perhaps read up on some basic socket programming to help figure this out.

**Comment by leaf918** [comment]
thanks for your answer.
I think I should send 2 pack for big pack, the first one that contains the 2nd pack size, then client need to read bytes using "read_n",and size parameter is from the 1st pack.
:)

**Comment by fpagliughi** [comment]
Yes, that is a common pattern for TCP stream programming: header and payload. First send a small, fixed-size header which contains the length of the payload, then send the variable-length payload. You would then receive the data with two `read_n()` calls. Assuming that you had a `header` struct witha `len` field for the payload length:

```
read_n(&header, sizeof(header));
auto n = header.len;
read_n(payload, n);
```
