### ISSUE TITLE
sys_error improperly declared; not caught as std::exception

### ISSUE THREAD

**Issue by snej** [fpagliughi/sockpp#18]
One of my tests keeps crashing with `uncaught exception of type sockpp::sys_error`. The exception is expected (the test tries to connect to a nonexistent hostname) but my `catch(const std::exception &x) { ... }` is being ignored.

I finally realized the problem: `sys_error` is not compatible with type `std::exception` because it doesn't _publicly_ inherit from it. Its declaration needs to be changed to

```c++
class sys_error : public std::runtime_error
```
i.e. adding `public` after the colon.

With this fix, my test works as expected.

**Comment by fpagliughi** [comment]
Yes mistake/bug on my part.
Fixed by PR #20
