### ISSUE TITLE
Regression: Failure in connect() no longer sets last_error

### ISSUE THREAD

**Issue by snej** [fpagliughi/sockpp#27]
A failure in `connector::connect()` or `acceptor::open` now leaves the `last_error` property at 0 instead of an actual error code.

This is a side effect of the fix of #23. `socket::close` now overwrites `last_error` with the status of the `::close` call, which is almost always 0.

**Comment by fpagliughi** [comment]
Thanks. The unit tests caught a couple side effects. I figured there would be more.

I think we need more unit tests.

**Comment by fpagliughi** [comment]
Fixed by #28. I hope.
