### ISSUE TITLE
select

### ISSUE THREAD

**Issue by bmahlbrand** [fpagliughi/sockpp#49]
Great library! Any interest in integrating `select`?

If so, I'm interested in working on that, but I'm curious what your thoughts are on how it would best fit into the library / future plans you might have.

**Comment by fpagliughi** [comment]
Note... six years later... a simple, non-owning `poller` class was easy enough to implement across platforms, and helped simplify some of the internal implementation like timeouts on connectors and acceptors.

It's up in master, and will ship with v2, though, it may get tweaked a little before then.
