### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by jaychanda** [fpagliughi/sockpp#5]
I have getting below error while building your library
build/Debug/GNU-Linux/NativeTCP.o:(.data.rel.ro._ZTVN6sockpp13tcp_connectorE[_ZTVN6sockpp13tcp_connectorE]+0x20): undefined reference to `sockpp::stream_socket::read(void*, unsigned long)'

**Comment by fpagliughi** [comment]
Sorry, I’m on holiday for a week, but will look as soon as I get back.
Which version/branch are you building? Which compiler are you using?

**Comment by fpagliughi** [comment]
I'm unable to recreate this build error. There is an implementation for `sockpp::stream_socket::read(void*, unsigned long)` and the file is included in the CMake build.

Are you using the GNU Makefiles? I don't think I updated them recently. I will get rid of them and use CMake only.  See #6

**Comment by fpagliughi** [comment]
I will assume this this was fixed with the updated build system. Feel free to re-open the issue if there is more information to share.
