### ISSUE TITLE
android build error: sockpp exception - no matching conversion for functional-style cast

### ISSUE THREAD

**Issue by bmahlbrand** [fpagliughi/sockpp#52]
When building for Android targets, I've encountered the following error:

```
/workspace/myproject/third-party/sockpp/src/exception.cpp:70:15: error: no matching conversion for functional-style cast from 'int' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
                        return s ? std::string(s) : std::string();
```

I'll look into an actual resolution and submit a PR if the fix isn't immediately obvious, but was able to get around it by commenting it out, and the rest of the library built fine.

**Comment by fpagliughi** [comment]
A quick Google brings up what appears to be the problem, and a possible solution:
https://stackoverflow.com/questions/32629222/how-to-use-strerror-r-properly-for-android

Can you try this out and submit a PR if it works. I don't have an Android development platform to test this.

**Comment by bmahlbrand** [comment]
```
    	#ifdef _GNU_SOURCE
			#if !defined(__GLIBC__)
			// use the XSI standard behavior.
				int e = strerror_r(err, buf, sizeof(buf));
				auto s = strerror(e);
				return s ? std::string(s) : std::string();
			#else
			// assume GNU exception
				auto s = strerror_r(err, buf, sizeof(buf));
				return s ? std::string(s) : std::string();
			#endif
        #else
            ignore_result(strerror_r(err, buf, sizeof(buf)));
        #endif
```

Seems to be on the right track, I'll do some more testing to check that it actually behaves as expected and submit a PR.
