### ISSUE TITLE
when will 1.0.0 be released?

### ISSUE THREAD

**Issue by laoshaw** [fpagliughi/sockpp#61]
so far the best socket-c-api wrapper I found for c++, hope it will have a stable release soon. Thanks!

**Comment by fpagliughi** [comment]
Yeah, sorry. The _code_ is stable.  It's just that I wanted to mess with the API a little to figure out how to integrate a couple possible SSL/TLS library choices. But that work was put on the back burner a little while ago.

To give it perspective, I've actually been using this library in production code for around 18 years, with just a minor refactoring when move semantics were introduced in C++11. It's just that I renamed the library when I refactored and reset the version back to zero. Still hasn't made it back to 1.0!

I guess I could do a little cleanup of what's here and just call this v1.0, then do the TLS work as v2.0 if it turns into a breaking API change.

**Comment by fpagliughi** [comment]
Finally.
