### ISSUE TITLE
Make exceptions optional

### ISSUE THREAD

**Issue by JakeSays** [fpagliughi/sockpp#72]
It would be great if this library could be used without exceptions. There are many environments where exceptions are not allowed.

**Comment by fpagliughi** [comment]
Ironically, this library fell out of a bigger framework for embedded systems that specifically did not use exceptions or runtime type identification. Somehow, though, over the years, exceptions made their way into it.

I count only a handful in the whole library, so it wouldn't be a crazy amount of work. But how should we handle:
1. Constructors that detect errors
2. Functions that just return a success value (and throw on error)

**Comment by ldgeng** [comment]
> Ironically, this library fell out of a bigger framework for embedded systems that specifically did not use exceptions or runtime type identification. Somehow, though, over the years, exceptions made their way into it.
> 
> I count only a handful in the whole library, so it wouldn't be a crazy amount of work. But how should we handle:
> 
> 1. Constructors that detect errors
> 2. Functions that just return a success value (and throw on error)

std::error_code?

**Comment by ldgeng** [comment]
just like winapi

**Comment by fpagliughi** [comment]
> std::error_code?

Wowwwww... I had no idea that was even in there!. I'll definitely have a look at that.

**Comment by fpagliughi** [comment]
> just like winapi

@ldgeng Can you point me to the winapi code that uses std::error_code?

**Comment by fpagliughi** [comment]
Moving to `std::error_code` would actually help with existing problems of platform error checks, and preset a road forward for TLS library error reporting. It also ties together a few other ideas. I am going to close this and move the conversation to Issue #77.

Please do comment on the ideas presented there. But, basically, it says "yes" to both of these ideas:
- Get rid of exceptions.
- Use `std::error_code` (for all errors)

**Comment by JakeSays** [comment]
@fpagliughi hey this is perfect!
