### ISSUE TITLE
Is there or will there be a way to join a multicast group?

### ISSUE THREAD

**Issue by fwr-ml** [fpagliughi/sockpp#80]
I looked through the source, but couldn't find it being implemented (, which doesn't necessarily mean much).

**Comment by fpagliughi** [comment]
No, sorry, there's nothing particular implemented for this, and I don't have any particular experience with multicast groups.  Is there something specific needed for UDP sockets in order to do this?

**Comment by fwr-ml** [comment]
I don't think, handling IGMP is needed. From what I've seen, on the sending side nothing special is needed.
On the receiving end a struct ip_mreq would have to be used (with IPv4 on Linux that is) like
```
struct ip_mreq mreq;
mreq.imr_multiaddr.s_addr = inet_addr(<multicast group address>);
mreq.imr_interface.s_addr = htonl(INADDR_ANY);
if (setsockopt(sock, IPPROTO_IP, IP_ADD_MEMBERSHIP,
               &mreq, sizeof(mreq)) < 0)
```

I'd love to be more complete, but I'm new to the socket business.

For now I use Arthur Brainville's kissnet, but I'd prefer your project, for there are release tags and your API lets me use dynamically sized buffers for reception.
kissnet's a one header library. It's sockets provide a method "join", that does what's needed.

It seems the only distinction Arthur makes is IPv4 vs IPv6. The rest is checking and pre-processing the given addresses.

**Comment by fpagliughi** [comment]
Definitely let us know how you make out, and if there's anything that could be added to the library that would help (keeping in mind the low-level nature of it). Or if there's anything you do that would be a good addition to the library, PR's are always welcome!

**Comment by fpagliughi** [comment]
I'll close this now, but feel free to re-open if there's anything new to report.
