### ISSUE TITLE
Broken example 'tcpecho'

### ISSUE THREAD

**Issue by MarcelskyXD** [fpagliughi/sockpp#96]
I was trying to run the tcpecho example but for some reason it doesn't work

```Sample IPv4 TCP echo client for 'sockpp' v2.0.0

Error connecting to server at: 'localhost':
        A non-blocking socket operation could not be completed immediately
```

The examples are from the master branch

**Comment by fpagliughi** [comment]
The `tcpecho` program is a client. It can talk to the `tcpechosvr` (server) program. First open a second console window and run the server. Then run the client.

**Comment by fpagliughi** [comment]
Also note that, as stated in the README, the master branch may not be stable, as we’re working toward a 2.0 version.

it would be better to download the latest release to try out the library.

**Comment by MarcelskyXD** [comment]
> The `tcpecho` program is a client. It can talk to the `tcpechosvr` (server) program. First open a second console window and run the server. Then run the client.
that is what i did

**Comment by fpagliughi** [comment]
Dunno. I just tried it on Linux (Mint 21/Ubuntu 22.04) and it works fine.

What platform/OS are you trying? 
Could another application be bound to that port? (I think it defaults to 12345). 
Could some security software or firewall be getting in the way?
Can you make network connections using any other software?

For example, if you run `tcpechosvr` in one window, you can interact with it using a standard, old, telnet:
```
$ telnet localhost 12345                                                                                       
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Hello world!
Hello world!
```

**Comment by fpagliughi** [comment]
Did you get this resolved? Anything more I need to look into?

**Comment by fpagliughi** [comment]
Closing from a lack of feedback. Please feel free to re-open if there are continues problems.
